"""Write a catalog forensic report. Live URL probes are best-effort."""

from __future__ import annotations

import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1] / "backend"
sys.path.insert(0, str(BACKEND_DIR))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from app.ontology.load import load_ontology  # noqa: E402
from app.ontology.validate import validate_ontology  # noqa: E402
from app.services.catalog.audit import audit_catalog  # noqa: E402
from audit_urls import classify_live  # noqa: E402


def main() -> int:
    bundle = load_ontology()
    static = audit_catalog(bundle)
    ontology_errors = validate_ontology(bundle)
    live_rows = []
    for resource in bundle.resources:
        if resource.url:
            live_rows.append(classify_live(resource))

    accessible = sum(1 for row in live_rows if row["accessible"] is True)
    unverified_access = [row for row in live_rows if row["accessible"] is not True]
    lines = [
        "# Catalog forensic audit (Slice 2.2)",
        "",
        "Generated by `python scripts/audit_catalog.py`.",
        "HTTPS is not treated as verification by itself.",
        "",
        "URL status model:",
        "",
        "- **verified** / `VERIFIED_RESOURCE`: the audit confirmed the endpoint (HTTP 200).",
        "- **claimed** / `CLAIMED_RESOURCE`: a URL is present but was not confirmed (403, 404, bot blocking, or transient failure).",
        "- **unavailable** / `UNAVAILABLE`: no usable URL exists. Do not invent a replacement.",
        "",
        "## Counts",
        "",
        f"- resources: {static.resource_count}",
        f"- ontology validation errors: {len(ontology_errors)}",
        f"- catalog audit errors: {len(static.errors)}",
        f"- catalog audit warnings: {len(static.warnings)}",
        f"- URLs probed: {len(live_rows)}",
        f"- URLs accessible this run: {accessible}",
        "",
        "## Documented catalog changes",
        "",
        "- Removed `fastapi-bigger-applications` as a weaker duplicate of `fastapi-tutorial` (same primary skill and type).",
        "- Removed the Linux prerequisite from `docker-get-started`. Docker Desktop get-started does not require a Linux competency; the overstated prereq made Docker UNKNOWN-blocked for AIML learners who needed Docker as an unblock intervention.",
        "- Slice 2.2: Kaggle Learn and Cloudflare Learning Center URLs that returned 403/404 to the audit user-agent are stored as `claimed`, not `verified`. They were not nullified.",
        "- No replacement URLs were invented.",
        "",
        "## Ontology validation",
        "",
    ]
    if ontology_errors:
        lines.extend(f"- {item}" for item in ontology_errors)
    else:
        lines.append("- none")
    lines.extend(["", "## Catalog audit errors", ""])
    if static.errors:
        lines.extend(f"- {item}" for item in static.errors)
    else:
        lines.append("- none")
    lines.extend(["", "## Catalog audit warnings", ""])
    if static.warnings:
        lines.extend(f"- {item}" for item in static.warnings)
    else:
        lines.append("- none")
    lines.extend(
        [
            "",
            "## URL classes",
            "",
            "| slug | format_valid | accessible | http | classification |",
            "|---|---|---|---|---|",
        ]
    )
    for row in live_rows:
        lines.append(
            f"| {row['slug']} | {row['format_valid']} | {row['accessible']} | "
            f"{row['http_status']} | {row['classification']} |"
        )
    for resource in bundle.resources:
        if not resource.url:
            lines.append(
                f"| {resource.slug} | n/a | n/a | n/a | UNAVAILABLE |"
            )
    lines.extend(["", "## Access not confirmed this run", ""])
    if unverified_access:
        for row in unverified_access:
            lines.append(f"- {row['slug']}: {row['classification']} ({row['url']})")
        lines.append("")
        lines.append(
            "These URLs were **not** silently nullified. They are **claimed/unconfirmed**, not verified, "
            "and not treated as unavailable unless there is no usable URL. This run does not invent replacements."
        )
    else:
        lines.append("- none")
    out = Path(__file__).resolve().parents[1] / "docs" / "CATALOG_AUDIT.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")
    print(f"resources={static.resource_count} errors={len(static.errors)} warnings={len(static.warnings)}")
    print(f"probed={len(live_rows)} accessible={accessible}")
    return 0 if not static.errors and not ontology_errors else 1


if __name__ == "__main__":
    raise SystemExit(main())
